# Generated by Django 5.0.4 on 2024-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("name", models.CharField(max_length=256)),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                (
                    "vendor_code",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("on_time_delivery_rate", models.FloatField(default=0.0)),
                ("quality_rating_avg", models.FloatField(default=0.0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("fulfillment_rate", models.FloatField(default=0.0)),
            ],
        ),
    ]
